In [3]:
### 1. Write a program to check whether an year entered by an user is leap year or not
year= int(input("Please Enter the year - "))
if year % 4 ==0 or year%400 == 0:
    print(year,"is a leap Year!")
else:
    print(year,"is not a leap year!")

Please Enter the year - 2012
2012 is a leap Year!


In [13]:
##.2Take a string containing punctuation marks as an input from user and 
##write a program to remove all the punctuation marks from a string
st=str(input("Enter the sting with punctuation -"))
punt='''!()-[]{};:'"\,<>./?@#$%^&*_~'''
nst=""
for i in st:
    if i not in punt:
        nst=nst+i   
print(nst)

Enter the sting with punctuation -[];//!@#$dfghgfds#$%^&*/*+
dfghgfds+


In [13]:
### 3. Take two separate numbers as input from the user and Write a program to swap 2 numbers 
##without using temporary variable
n= int(input("Please Enter the num1 - "))
s= int(input("Please Enter the num2 - "))
n=n+s
s=n-s
n=n-s
print("First no=",n,"\n","Second no=",s)

Please Enter the num1 - 3
Please Enter the num2 - 5
1= 5 
 2= 3


In [14]:
### 4. Write a program to print product of following variables
i = 10 
st = "15"
print(i*int(st))

150


In [152]:
##5. Write a program to print following pattern
import string
b=""
for i in string.ascii_lowercase:
        b=b+i
        print(b)      

a
ab
abc
abcd
abcde
abcdef
abcdefg
abcdefgh
abcdefghi
abcdefghij
abcdefghijk
abcdefghijkl
abcdefghijklm
abcdefghijklmn
abcdefghijklmno
abcdefghijklmnop
abcdefghijklmnopq
abcdefghijklmnopqr
abcdefghijklmnopqrs
abcdefghijklmnopqrst
abcdefghijklmnopqrstu
abcdefghijklmnopqrstuv
abcdefghijklmnopqrstuvw
abcdefghijklmnopqrstuvwx
abcdefghijklmnopqrstuvwxy
abcdefghijklmnopqrstuvwxyz


In [108]:
### 6. Write a program to print tables from 2 to n, where n is provided by user
n=int(input("Enter the no of tables-\n"))
for i in range(2,n+1):
    for j in range(1,11):
        print(i, 'x', j, '=', i*j)
    print()

Enter the no of tables-
10
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20

3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30

4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40

5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50

6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60

7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70

8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
8 x 10 = 80

9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90

10 x 1 = 10
10 x 2 = 20
10 x 3 = 30
10 x 4 = 40
10 x 5 = 50
10 x 6 = 60
10 x 7 = 70
10 x 8 

In [67]:
##Extra: Given two sets, Checks if One Set is a subset or superset of another Set.
##if the subset is found delete all elements from that set
ft = {27, 43, 34, 0}
st = {34, 93, 22, 0, 27, 43, 53, 48}
s=set()
if len(ft)<len(st):
    for i in ft:
        if i in st:
            s.add(i)
print(s)   

{0, 27, 34, 43}


In [50]:
### 7. Write a program to read height (in centimeters) from user and then convert it to feet and inches
n=float(input("Enter the height in 'Centimenters'-\n"))
f=n/30.48
feet=int(feet)
i=f-feet
inch=int(i*12)
print("The height is",feet,"feet","&",inch,"inch")

Enter the height in 'Centimenters'-
45.72
The height is 1 feet & 6 inch


In [54]:
### 8. Write a program to print following pattern
n=int(input("Enter the range of pattern-\n"))
for i in range(n):
    print("*"*i)
for i in range(n):
    print("*"*(n-i))

Enter the range of pattern-
50

*
**
***
****
*****
******
*******
********
*********
**********
***********
************
*************
**************
***************
****************
*****************
******************
*******************
********************
*********************
**********************
***********************
************************
*************************
**************************
***************************
****************************
*****************************
******************************
*******************************
********************************
*********************************
**********************************
***********************************
************************************
*************************************
**************************************
***************************************
****************************************
*****************************************
******************************************
***********************

In [63]:
### 9. Below list contains age and name of five students. 
#Convert the list into a dictionary such that the name is taken as key and 
#the age before their name is taken as thier respective value in the dictionary
students = [26,'Jon',34,'Roger',13,'Jessica',24,'Monica',65,'Ashton']
dic={}
for i in range(0,len(students),2):
    dic[students[i]]=students[i+1]
print(dic.items())

dict_items([(26, 'Jon'), (34, 'Roger'), (13, 'Jessica'), (24, 'Monica'), (65, 'Ashton')])


In [109]:
### 10. Write a program to check whether two strings, taken from user, are anagram or not
text1=str.lower(input("Enter first word -\n"))
text2=str.lower(input("Enter second word -\n"))
s1=[]
s2=[]
for i in text1:
    s1.append(i)
for j in text2:
    s2.append(j)
if s1.sort() == s2.sort() and len(s1)==len(s2):
    print("An Anagram")
else:
    print("not an Anagram")

Enter first word -
daddy
Enter second word -
dddya
An Anagram


In [78]:
text1=str.lower(input("Enter first word -"))
text2=str.lower(input("Enter second word -"))
if sorted(text1) == sorted(text2):
    print("An Anagram")
else:
    print("not an Anagram")

Enter first word -Ajit
Enter second word -ajita
not an Anagram


In [ ]:
### 11. Write a program that sorts all the elements of the list according to the first letter,
##irrespective of their cases (uppercase or lowercase). Note: Do not use any inbuilt sorting function

In [98]:
### 12. Write a program that prints a list of sour fruits from the below tuple:
fruits = (('Lemon','sour'), ('DragonFruit', 'Sweet'), ('Grapes','sour'), ('Kiwi','sOuR'), 
          ('Apples','sweet'), ('Orange','Sour'), ('Blueberries','sweet'), ('Limes','sour') ) 
lst=[]
for i in fruits:
    fla=i[1]
    if fla.lower()=="sour":
        lst.append(i[0])  
print(lst)

['Lemon', 'Grapes', 'Kiwi', 'Orange', 'Limes']


In [115]:
### 13. Given below are the list of positive and negative words. 
##Also a list of tweets is provided. Separate out the positive and negative comments
positive = ['good','awesome', 'best','nice']
negative = ['worst','awful', 'bad']
tweets = ['This government policies are good', 'bad implementation', 
          'The way he played showed that he is one of the best players in the world', 
          'Her acting in the play was awesome', 'The wine tastes awful', 'Its nice to hear this little kids laugh']
for i in tweets:
    w=i.split(" ")
    for p in positive:
        for k in w:
            if p.lower() == k.lower():
                print("''",i,"''","-is a Positive comment.")
    for n in negative:
        for k in w:
            if n.lower() == k.lower():
                print("''",i,"''","-is a Negative comment.")

'' This government policies are good '' -is a Positive comment.
'' bad implementation '' -is a Negative comment.
'' The way he played showed that he is one of the best players in the world '' -is a Positive comment.
'' Her acting in the play was awesome '' -is a Positive comment.
'' The wine tastes awful '' -is a Negative comment.
'' Its nice to hear this little kids laugh '' -is a Positive comment.


In [150]:
### 14. Write a program that performs multiplication of the following two matrix
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
Y = [[1,8,1],
    [3,7,3],
    [4,5,9]]
lst=[]
for i,j in zip(X,Y):
    for l,m in zip(i,j):
        n=l*m
        lst.append(n)
print(np.array([lst]).reshape(3,3))

[[ 1 16  3]
 [12 35 18]
 [28 40 81]]


In [128]:
### 15. Write a program to remove space from keys of the given dictionary
emp= {'emp 01' : 'Raj', 'emp 02' : 'Sheela', 'emp 0 3 ': 'Joseph'}; 
emp1={}
for k,v in emp.items():
    emp1[(k.replace(" ",""))]=v
print(emp1)    

{'emp01': 'Raj', 'emp02': 'Sheela', 'emp03': 'Joseph'}


In [129]:
emp= {'emp 01' : 'Raj', 'emp 02' : 'Sheela', 'emp 0 3 ': 'Joseph'}; 
for k,v in emp.items():
    emp[(k.replace(" ",""))]=emp.pop(k)
print(emp)   

{'emp01': 'Raj', 'emp02': 'Sheela', 'emp03': 'Joseph'}


In [ ]:
##16. Write a program to display the subjects for which the scores are between 300 and 
##500 (inclusive) in the given dataframe

In [11]:
### 17. Write a program to find numbers between 10000 to 20000 from a given array
import numpy as np
sales = np.array([1432,143223,2043332,1642357,54327,754338,12459,75435,224454,1433,12447,25532,86674,74338,12678])
for i in sales:
    if i in range(10000,20001):
        print(i)

12459
12447
12678


In [ ]:
###18

In [ ]:
###19

In [ ]:
###20

In [16]:
### 21. Convert a 1D array to a 2D array containing 2 rows
dim_1 =np.array([331, 245, 246, 475, 348, 229])
dim_1.shape
dim= dim_1.reshape(2,3)
dim

array([[331, 245, 246],
       [475, 348, 229]])

In [19]:
### 22. Find the average cost of each variety of product available in the three different shops
cost=[[10, 20, 30], [17, 14, 21], [25, 15, 12]]
columns=['product_a', 'product_b', 'product_c']
index=['Shop1', 'Shop2', 'Shop3']   

IndentationError: expected an indented block (<ipython-input-19-98f480b8c408>, line 12)

In [ ]:
###23

In [ ]:
### 24. Write a program to delete items from series_a that are present in series_b and print the updated series_a
sa = ([11, 12, 13, 14, 15])
sb= ([14, 15, 16, 17, 18])
type(sb)
for i in sb:
    if i in sa:
        sa.remove(i)      
print(sa)

In [ ]:
##25

In [ ]:
### 26. Get common elements from the two arrays
testa = np.array([11,12,13,22,23,44,43,24,45,36])
testb = np.array([17,22,13,22,47,34,39,44,29,28])
lst=[]
for i in  testa:
    if i in testb:
        lst.append(i)
comm=np.array([lst])
comm

In [ ]:
###27

In [ ]:
###28

In [ ]:
###29

In [147]:
### 30. Reverse each of the rows of the 2D array
num_array = np.arange(20).reshape(4,5)
for i in range(len(num_array)):
    d=num_array[i]
    d=d[::-1]
    print(d)

[4 3 2 1 0]
[9 8 7 6 5]
[14 13 12 11 10]
[19 18 17 16 15]


In [144]:
num_array = np.arange(20).reshape(4,5)
lst=[]
for i in num_array:
    for j in i[::-1]:
        lst.append(j)
num_array=np.array([lst]).reshape(4,5)
print(num_array)

[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]
